version: '3.5'
services:
  app:
    container_name: cliqz-privacy-warning
    build: .
    ports:
      - '9009:9009'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
    command: >-
      sh -c "
        npm run storybook > /var/log/storybook.log 2>&1 & npm start
      "
